//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.02 at 02:12:53 PM EET 
//

package com.kyrylov.nure.ua;

import com.kyrylov.nure.ua.util.IXml;
import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Products", propOrder = {
        "makeUpProduct"
})
@XmlRootElement(name = "Products")
public class Products implements IXml {

    @XmlElement(required = true)
    protected List<Products.MakeUpProduct> makeUpProduct;

    public List<Products.MakeUpProduct> getMakeUpProduct() {
        if (this.makeUpProduct == null) {
            this.makeUpProduct = new ArrayList<>();
        }
        return this.makeUpProduct;
    }

    @Getter
    @Setter
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "MakeUpProduct", propOrder = {
            "status",
            "reviews",
            "name",
            "brand",
            "price"
    })
    public static class MakeUpProduct {
        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected Reviews reviews;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String brand;
        @XmlElement(required = true)
        protected Integer price;
        @XmlAttribute(name = "link")
        protected String link;
        @XmlAttribute(name = "count")
        protected Integer count;


        @Getter
        @Setter
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "Reviews", propOrder = {
                "stars",
                "comments"
        })
        public static class Reviews {
            @XmlElement(required = true)
            protected Integer stars;
            @XmlElement(required = true)
            protected Integer comments;
        }

    }

}

